-- MySQL Script generated by MySQL Workbench
-- Sun Nov 15 15:04:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

DROP TABLE IF EXISTS Employee ;

DROP TABLE IF EXISTS Owner ;

DROP TABLE IF EXISTS Client ;

DROP TABLE IF EXISTS Manages ;

DROP TABLE IF EXISTS Employee_Email ;

DROP TABLE IF EXISTS Partner ;

DROP TABLE IF EXISTS Associate ;

DROP TABLE IF EXISTS Property ;

DROP TABLE IF EXISTS Commercial ;

DROP TABLE IF EXISTS Residential ;

DROP TABLE IF EXISTS Industrial ;

DROP TABLE IF EXISTS Owns ;

DROP TABLE IF EXISTS Represents ;

DROP TABLE IF EXISTS Assigned ;

DROP TABLE IF EXISTS Views ;

DROP TABLE IF EXISTS Lease ;

DROP TRIGGER IF EXISTS Lease_AFTER_INSERT;
